#!/bin/bash
# note: eclair counts commit tx fees as part of toLocal
jq '
{
  "to_local": (map(.data.commitments.localCommit.spec.toLocal |. /1000|floor)|add| ./100000),
  "to_remote": (map(.data.commitments.localCommit.spec.toRemote |./1000|floor)|add| ./100000),
  "htlcs_in": (map(.data.commitments.localCommit.spec.htlcs|.[]|select(.direction=="IN")|.add.amountMsat |./1000|floor)|add | (. + 0) /100000),
  "htlcs_out": (map(.data.commitments.localCommit.spec.htlcs|.[]|select(.direction=="OUT")|.add.amountMsat |./1000|floor)|add | (. + 0) /100000)
}'
